### ISSUE TITLE
Reading Google Analytics data by Google BigQuery connector

### ISSUE THREAD

**Issue by pscorca** [AnalyticJeremy/ADF_BigQuery#1]
Hi,
is it possible to reading GA data by the Google BigQuery connector? How?
Or is it possible to use the PowerShell script to read GA data? How?
Thanks

**Comment by AnalyticJeremy** [comment]
Yes, it's definitely possible to read Google Analytics data with the BigQuery connector.  That was the exact use case I was pursuing when I was writing this article.

1.  To read the data, you must first create a "Connection" using the BigQuery connector (as described in this article).  Note that when you enter the "Project ID", it must be the BigQuery project where your GA data is stored.

2. Next, you must create a dataset.  This will be linked to the Connection you just created.  You will also define the schema of the GA data here.  So you will need to list out every column you will be selecting from the Google Analytics tables.

3.  Lastly, you create a "Copy" activity in your pipeline.  This is where you specify the SQL statement that selects data from the GA tables.  You also specify where the data will be copied to.  This requires that you create a Connection and Dataset for the destination (just like we did for the source in steps 1 and 2 above).

**Comment by pscorca** [comment]
Hi Jeremy, thanks for your reply.
I've accessed to the GCP to get the project id of the GA project for the web site of my company, I've created a related Id client OAuth 2.0 and the next client secret. With your powershell script I've generated the refresh token: inside ADF I can create successfully a BigQuery linked service but I don't see any GA tables.
Perhaps, I've skipped some steps to accomplish.
Any helps to me, please?

**Comment by AnalyticJeremy** [comment]
You won't see the GA tables in Azure Data Factory.  ADF doesn't have any features that let you browse the source system and pick what you want.

Instead, you have to write a SQL statement in Google Analytics that selects the fields you want.  Then you copy that SQL statement and paste it in the "Source" settings of your Copy activity.

For example, here's a simple SQL statement that selects 5 fields from Google Analytics:
```
SELECT
     visitorId AS visitorId,
     visitNumber AS visitNumber,
     visitId AS visitId,
     visitStartTime AS visitStartTime,
     date AS date
FROM `bigquery-public-data.google_analytics_sample.ga_sessions_20170801`
```

If you haven't added a Copy activity to your pipeline, you should go ahead and do that.  That's where all the magic happens, and it will help you understand what settings you need to provide to successfully copy data from Google Analytics to your destination.

**Comment by pscorca** [comment]
Hi Jeremy,
in fact I'm trying to create a data pipeline having a copy activity. For this activity, I've tried to create a data source having Google BigQuery as a linked service. For this linked service, I've specified the GA project id, the OAuth client id, the client secret and the related refresh token generated by your PowerShell script. But I thought that the Browse Table button of the dataset of the copy activity should show the GA tables.
Now, where in GA can I write the SQL statement? I'm new in GA and in BigQuery Technologies. Do I need to write the SQL Statement in GA or in BigQuery? Thanks

**Comment by AnalyticJeremy** [comment]
You write SQL statements for BigQuery in BigQuery.

Go to the [BigQuery](https://bigquery.cloud.google.com/) console.  On the left pane, there should be a red button that says "Compose Query."  This will allow you to interactively query your Google Analytics data through the BigQuery interface.

I don't have much experience with BigQuery myself.  This is about as much as I've figured out.

**Comment by pscorca** [comment]
Hi Jeremy,
you have reported a SQL statement to query Google Analytics data (that I've tried but unsuccessfully).
How have you queried GA from the BigQuery console?

**Comment by pscorca** [comment]
Hi Jeremy, I've done major checks. You have provided me a GA query to read a sample and public GA dataset: the related syntax functions rightly for a Google BigQuery dataset inside a copy activity of an ADF data pipeline, but to test it successfully inside BigQuery console it occurs to change the "`" character in "[", "]" characters for the GA table name.
However, to expose other GA data, not sample ones and not public ones, I think that it is need to pay.

**Comment by AnalyticJeremy** [comment]
As I understand it, BigQuery bills on a per query basis.  If that is correct, then, yes, you will need to pay for your queries as you develop and run your ADF pipeline.
