### ISSUE TITLE
the power shell script is not allowing Google account "ALLOW " button is in disable state.We need to make that button enable so that we can get refresh token please help me to review the code and get the refresh token by enabling the Allow button after giving google account credentials.

### ISSUE THREAD

**Issue by sheshkumar01** [AnalyticJeremy/ADF_BigQuery#3]
Hi ,

I am using below POWER SHELL Code unfortunately Google account is popped and it is asked for username and Password after that  I have provided username and password but ALLOW button is in disable state and not getting enable that's reason i am not able to generate refresh token.Could you please anyone help me to review the below code and help me to get refresh token.

Thank you. 

# A PowerShell script for retrieving a refresh token from Google

#

# https://blogs.technet.microsoft.com/ronba/2016/05/09/using-powershell-and-the-office-365-rest-api-with-oauth/

# Before running this script, you need to set these three values.  They can be
# obtained from the GCP console.
$clientId = "CLIENT_ID"
$clientSecret = "CLIENT_SECRET"
$redirectUrl = "http://127.0.0.1"

# This is the access scope we will be requesting
$scope = "https://www.googleapis.com/auth/bigquery"

# Declare a function that will show the OAUTH window to prompt for credentials
Add-Type -AssemblyName System.Web
Function Show-OAuthWindow
{
    param(
        [System.Uri]$Url
    )

    Add-Type -AssemblyName System.Windows.Forms

    $form = New-Object -TypeName System.Windows.Forms.Form -Property @{Width=440;Height=640}
    $web  = New-Object -TypeName System.Windows.Forms.WebBrowser -Property @{Width=420;Height=600;Url=($url ) }
    $DocComp  = {
        $Global:uri = $web.Url.AbsoluteUri
        if ($Global:Uri -match "error=[^&]*|code=[^&]*") {$form.Close() }
    }
    $web.ScriptErrorsSuppressed = $true
    $web.Add_DocumentCompleted($DocComp)
    $form.Controls.Add($web)
    $form.Add_Shown({$form.Activate()})
    $form.ShowDialog() | Out-Null

    $queryOutput = [System.Web.HttpUtility]::ParseQueryString($web.Url.Query)
    $output = @{}
    foreach($key in $queryOutput.Keys){
        $output["$key"] = $queryOutput[$key]
    }
    
    $output
}

# Build the URL for Google's OAuth service
$authUrl = "https://accounts.google.com/o/oauth2/v2/auth"
$authUrl += "?client_id=" + $clientId
$authUrl += "&redirect_uri=" + [uri]::EscapeDataString($redirectUrl)
$authUrl += "&scope=" + [uri]::EscapeDataString($scope)
$authUrl += "&access_type=offline&include_granted_scopes=true&response_type=code&prompt=consent"

# Open the window so the user can authenticate to Google's service
$queryOutput = Show-OAuthWindow -Url $authUrl
$accessCode = $queryOutput.code

# Construct URL and parameters for HTTP POST that will be used to exchange the
# access code for an access token and a refresh token
$authUrl = "https://www.googleapis.com/oauth2/v4/token"
$postParams = @{code=$accessCode;
                client_id=$clientId;
                client_secret=$clientSecret;
                redirect_uri=$redirectUrl;
                grant_type="authorization_code"}

# make the HTTP request
try {
   $refreshOutput = Invoke-WebRequest -Uri $authUrl -Method POST -Body $postParams
}
catch {
   echo '### ERROR TRYING TO REDEEM ACCESS CODE ###'
   $ErrorMessage = $_.Exception.Message
   $FailedItem = $_.Exception.ItemName
   $result = $_.Exception.Response.GetResponseStream()
   $reader = New-Object System.IO.StreamReader($result)
   $responseBody = $reader.ReadToEnd();
   echo '## responseBody ##' $responseBody
   throw
}

# If we were successful, extract the refresh token from the HTTP response
$refreshOutputContent = ConvertFrom-Json $refreshOutput.Content
$refreshToken = $refreshOutputContent.refresh_token

# Display our findings!
$output = @{"Client Id" = $clientId;
            "Client Secret" = $clientSecret;
            "Refresh Token" = $refreshToken}
echo ""
echo "--------------------------------------------------------------------------------"
echo "In Azure Data Factory, create a linked service to Google BigQuery."
echo "Set the ""Authentication type"" to ""User Authentication""."
echo "Use the following values for the remaining fields:"
$output

**Comment by vandalytic** [comment]
Hi all, same problem here. Any solution????

**Comment by knehasingh07** [comment]
Hi, facing same issue. Can anyone help please.

**Comment by amr-guenena** [comment]
I am facing same issue!

**Comment by nehas0** [comment]
Hi, 
I was not able to solve the above powershell issue , but I got the refresh token using link
https://jpda.dev/getting-your-bigquery-refresh-token-for-azure-datafactory-f884ff815a59
We can simply put the GET command directly on browser and use Postman web app for POST command . ( The app is free and hardly take 5 min to understand )

**Comment by AnalyticJeremy** [comment]
These issues have been resolved with commit b3e956c

### Problem
Previously, the PowerShell script would launch a web browser window that would allow users to authenticate to Google.
This made the process very easy for the user because it automated the work of opening and retrieving URLs.  However,
the only browser supported by PowerShell is IE 11.  This browser is now very old, and Google no longer trusts it.  It will not
allow you to authenticate when using that browser.  So the PowerShell script would fail or not display the "Allow" button.

### Fix
To work around this issue, I had to make the code more cumbersome.  Now there are two scripts.  The first script generates
a URL.  Users must copy this URL from PowerShell and open it in their own web browser.  They can then complete the Google
authorization process.  They will then be redirected to a URL.  They must copy this redirect URL from their browser's
address bar and paste it in a *second* PowerShell script.  This script will generate the refresh token.

This new process is not nearly as convenient as the old process.  However, it's the only viable work-around in our modern,
more secure computing environments.
